# .github/workflows/deposit-and-lock-cpmm-lp.yml
name: Deposit and Lock Liquidity to Raydium CPMM LP

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch: # (manual trigger too)

jobs:
  deposit_and_lock_liquidity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Deposit and Lock Liquidity
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
        run: |
          echo "$PRIVATE_KEY" > keypair.json
          npx tsx index.ts
