# .github/workflows/harvest-all-cpmm-lp.yml
name: Harvest All Raydium CPMM LP

on:
  schedule:
    - cron: '0 0 1 * *' # Run at midnight on the first day of every month
  workflow_dispatch: # (manual trigger too)

jobs:
  harvest_all_cpmm_lp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Harvest All Raydium CPMM LP
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          HELIUS_API_KEY: ${{ secrets.HELIUS_API_KEY }}
        run: |
          echo "$PRIVATE_KEY" > keypair.json
          npx tsx raydium/cpmm/harvestAllRfkLP.ts
